<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="PageListeContacts.aspx.cs" Inherits="EvalASPNET.WebForm.PageListeContacts" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Liste contacts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
        asp-fallback-href="~/Ressources/Content/bootstrap.min.css"
        asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    <link rel="stylesheet" href="~/Ressources/Content/site.min.css" asp-append-version="true" />
</head>

<body>
    <div class="container" style="background: url('../Ressources/imgs/contact-bluewin.jpg') center center; background-size: cover;">
        <form id="form1" runat="server">
            <br />
            <asp:Button ID="ButtonAjouter" runat="server" Text="Ajouter un contact" OnClick="ButtonAjouter_Click1" />
            <span style="display:inline-block; width: 100px;"></span>
             <asp:Button ID="ButtonDeconnexion" runat="server" Text="Déconnexion" OnClick="ButtonDeconnexion_Click" />
            <br />
            <br />
            <div class="table-responsive">
                <asp:GridView ID="GridViewListeContact" runat="server" class="table" AllowPaging="True"
                    AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
                    AutoGenerateEditButton="True" DataSourceID="SqlDataSource1"
                    OnRowUpdating="GridViewListeContact_RowUpdating" OnRowDeleting="GridViewListeContact_RowDeleting" ForeColor="Blue" Font-Bold="True" Font-Size="Medium" >

                    <Columns>
                        <asp:BoundField DataField="idcontact" HeaderText="idcontact" SortExpression="idcontact" ReadOnly="True" />
                        <asp:BoundField DataField="Civilite" HeaderText="Civilite" SortExpression="Civilite" />
                        <asp:BoundField DataField="Nom" HeaderText="Nom" SortExpression="Nom" />
                        <asp:BoundField DataField="Prenom" HeaderText="Prenom" SortExpression="Prenom" />
                        <asp:BoundField DataField="DateNaissance" DataFormatString="{0:dd/MM/yyyy}" HeaderText="Date de naissance" SortExpression="DateNaissance" />
                        <asp:BoundField DataField="Adresse" HeaderText="Adresse" SortExpression="Adresse" />
                        <asp:BoundField DataField="CP" HeaderText="CP" SortExpression="CP" />
                        <asp:BoundField DataField="Ville" HeaderText="Ville" SortExpression="Ville" />
                        <asp:BoundField DataField="Pays" HeaderText="Pays" SortExpression="Pays" />
                        <asp:BoundField DataField="Telephone" HeaderText="Telephone" SortExpression="Telephone" />
                        <asp:BoundField DataField="Portable" HeaderText="Portable" SortExpression="Portable" />
                        <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                    </Columns>

                </asp:GridView>
                <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="Data Source=GYGABITE-PC\SQLEXPRESS;Initial Catalog=ucontact;Integrated Security=True;" SelectCommand="SELECT [idcontact], [Civilite], [Nom], [Prenom]
,
(
case  [DateNaissance]
	when cast('1900-01-01' as date) then null
	else  [DateNaissance]
end
) as DateNaissance,
[Adresse], [CP], [Ville], [Pays], [Telephone], [Portable], [Email] FROM [CONTACT] ORDER BY [Nom], [Prenom]"
                    UpdateCommand="select 1+1" DeleteCommand="select 1+1" InsertCommand="select 1+1">
                    <InsertParameters>
                        <asp:ControlParameter ControlID="Label1" DefaultValue="0" Name="newparameter" PropertyName="Text" />
                    </InsertParameters>
                </asp:SqlDataSource>
            </div>

            <br />
        </form>
    </div>
</body>
</html>
