using Contacts.entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using Contacts;
using System.Data;
using System.Diagnostics;
using EvalASPNET.classes;
using Contacts.classes;

namespace EvalASPNET.WebForm
{
    public partial class PageListeContacts : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            string req= "select * from contact where iduser={0}";
            SqlDataSource1.ConnectionString = dao.DaoBD.MyConnection.ConnectionString;

            var c = HttpContext.Current;
            User u = c.Session["userApi"] as User;
            EvalASPNET.Entity.User user = c.Session["userLocal"] as EvalASPNET.Entity.User;
            if (u==null && user==null)
                Server.Transfer("PageAccueilr.aspx", true);

            int iduser = 0;
            if (u != null)            
                iduser = (int)u.getIduser();
            else if (user != null)
                iduser = user.iduser;

            SqlDataSource1.SelectCommand = string.Format(req, iduser);

            if (u == null)
            {
                this.GridViewListeContact.AutoGenerateDeleteButton = false;
                this.GridViewListeContact.AutoGenerateEditButton = false;
                this.ButtonAjouter.Visible = false;
            }
        }

        protected void GridViewListeContact_RowUpdating(object sender, GridViewUpdateEventArgs e)
        {
            Debug.Write("gg");
            User u = Session["userApi"] as User;

            GestionContact.SaveContactAPI(u, e.OldValues, e.NewValues);

            //charge une liste des contacts avec leurs données via l'API
            List<EvalASPNET.Entity.Donnee> liste = GestionContact.ChagerListeContacts(u);

            if (liste != null && liste.Count > 0)
            {
                //enregistre les données de l'API vers la base locale
                dao.DaoContact.saveContacts(liste);
            }
        }

        protected void ButtonAjouter_Click1(object sender, EventArgs e)
        {
            Server.Transfer("PageAjouter.aspx", true);
        }

        protected void GridViewListeContact_RowDeleting(object sender, GridViewDeleteEventArgs e)
        {
            int idcontact = 0;
            Int32.TryParse((string) e.Values["idcontact"], out idcontact);

            //supprime le contact par l'API
            ApiContact.DeleteContactById(idcontact);

            //suprimme le contact dans la base locale
            dao.DaoContact.deleteContactByID(idcontact);

        }

        protected void ButtonDeconnexion_Click(object sender, EventArgs e)
        {
            Session["userApi"] = null;
            Session["userLocal"] = null;
            Server.Transfer("PageAccueil.aspx", true);
        }
    }
}